# Generated by Django 5.1.1 on 2024-09-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_perfilusuario_cpf_alter_perfilusuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
