# Generated by Django 5.1.1 on 2024-09-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_perfilusuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_nascimento',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
