# Generated by Django 5.1.1 on 2024-09-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(related_name='produtos', to='spartangear.categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, help_text='Desconto percentual', max_digits=4, verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fotos',
            field=models.ImageField(blank=True, default='fotos_produtos/placeholder.jpg', upload_to='fotos_produtos/', verbose_name='Fotos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='variacao_cor',
            field=models.ManyToManyField(related_name='produtos_cor', to='spartangear.variacaocor', verbose_name='Variações de Cor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='variacao_tamanho',
            field=models.ManyToManyField(related_name='produtos_tamanho', to='spartangear.variacaotamanho', verbose_name='Variações de Tamanho'),
        ),
    ]
