# Generated by Django 5.1.1 on 2024-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0002_alter_produto_options_alter_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto percentual', max_digits=4, verbose_name='Desconto (%)'),
        ),
    ]
