# Generated by Django 5.1.1 on 2024-09-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0003_alter_produto_desconto_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desconto percentual', max_digits=4, verbose_name='Desconto (%)'),
        ),
    ]
