# Generated by Django 5.1.1 on 2024-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0004_alter_produto_desconto_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Desconto percentual', max_digits=4, verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='variacaocor',
            name='cor',
            field=models.CharField(max_length=20),
        ),
    ]
