# Generated by Django 5.1.1 on 2024-09-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0006_cor_tamanho_remove_produto_variacao_cor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='esportes',
            field=models.ManyToManyField(related_name='produtos', to='spartangear.esporte'),
        ),
    ]
