# Generated by Django 5.1.1 on 2024-09-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0007_esporte_produto_esportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='codigo_cor',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
