# Generated by Django 5.1.1 on 2024-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0009_produto_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d'),
        ),
    ]
