# Generated by Django 5.1.1 on 2024-09-17 06:56

import spartangear.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartangear', '0011_alter_foto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ref',
            field=models.CharField(default=spartangear.models.gerar_id_unico, editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/%Y/%m/%d'),
        ),
    ]
